name: 'Jekyll to s3 and cloudfront'
description: 'Generate static site with jekyll, push it to aws s3 and invalidate cloudfront'
inputs:
  aws_s3_bucket:
    description: 'aws s3 bucket to push the generated static site'
    required: true
  aws_cloudfront_distribution_id:
    description: 'distribution id of the cloudfront API'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.aws-s3-bucket }}
    - ${{ inputs.aws-cloudfront-distribution-id }}
branding:
  icon: 'git-commit'
  color: 'green'